### ISSUE TITLE
Cannot login with my accounts

### ISSUE THREAD

**Issue by YanderePepe** [ORelio/Minecraft-Console-Client#203]
The title basically tells it all. Non of my accounts will work in the client even though they work in the MC launcher. I think i have the newest version.  I checked my passwords in the accounts.txt multiple times and when i copy & paste the credentials into the launcher they work yet they don't in the Client.

Thanks for any help

**Comment by ORelio** [comment]
Hello,

Just tried with my own accounts, it works. The official launcher might retain a session token across launches, so that if login (but not session) servers are down, Minecraft Console Client might not be able to login whereas the official launcher may still work using its stored session token. By default, Minecraft Console Client will store session tokens in memory, but not on disk (configurable).

You may want to try setting your password to `A-Za-z0-9` characters only to check for encoding issues.
Otherwise, I haven't anything else to suggest, if you have no specific error message or crash report.

**Comment by YanderePepe** [comment]
I changed my Password. Still didnt work. I will include a screenshot of what is going on after i switched the client version from 1.8.8 to 1.9.0. 

![capture](https://cloud.githubusercontent.com/assets/20440840/18810503/3bbf41de-8266-11e6-8c34-63a33374ef50.PNG)

**Comment by ORelio** [comment]
Okay so every network attempts will time out on your side:
 - Minecraft login (maybe "incorrect password" is wrongly reported, is it responding fast?)
 - Server ping timeouts and you have to manually provide server version
 - ThreadAbord in connection attempt (likely because of how I implemented timeout)
Maybe Minecraft Console Client is not allowed to access the Internet on your computer?

**Comment by YanderePepe** [comment]
I tried the latest Developmental Build and it still won't connect. I checked and I have Internet Access to everything else. I even manually added the Program to the Firewall exceptions. If you have any suggestions  to what might help, I'd be very thankful.

**Comment by ORelio** [comment]
I'm starting to get out of suggestions, maybe would you be able to install Visual Studio on your computer and try out some debug code for me? If so, get the [Indev branch source code](https://github.com/ORelio/Minecraft-Console-Client/archive/Indev.zip) and open the project in Visual Studio, then go to `Protocol\ProtocolHandler.cs` and replace
````C#
if (result.Contains("UserMigratedException"))
{
    return LoginResult.AccountMigrated;
}
else return LoginResult.WrongPassword;
````
With:
````C#
if (result.Contains("UserMigratedException"))
{
    return LoginResult.AccountMigrated;
}
else
{
    System.IO.File.WriteAllText("login-error.txt", result);
    ConsoleIO.WriteLineFormatted("§8Login error saved as 'login-error.txt' for further analysis.");
    return LoginResult.WrongPassword;
}
````
Then you would get raw output from Mojang servers in `login-error.txt` so that you can past it here. Hopefully that would provide more details about the login error you are facing.

Note: To compile and start debugging in Visual Studio, just press `F5`.

**Comment by ORelio** [comment]
Due to lack of feedback, I'll assume the issue is now resolved. Closing, but feel free to reopen if needed.
